# Generated by Django 3.2.19 on 2023-06-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_postBee', '0002_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'En attente de validation'), ('1', 'En ligne'), ('2', 'Archivé')], default='0', max_length=1),
        ),
    ]
