# Generated by Django 3.2.19 on 2023-06-11 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('api_postBee', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='authtoken.token'),
        ),
    ]
