# Generated by Django 3.2.19 on 2023-06-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_postBee', '0004_account_api_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='api_token',
        ),
    ]
