# Generated by Django 3.2.19 on 2023-06-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_postBee', '0006_auto_20230614_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='url',
        ),
    ]
