# Generated by Django 3.2.19 on 2023-06-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_postBee', '0007_rename_attachment_attachment_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
